In [10]:
import pandas as pd
from statsmodels.stats.outliers_influence import varivance_inflation_factor

ModuleNotFoundError: No module named 'statsmodels'

In [4]:
data = pd.read_csv(r"C:\Users\dipak\OneDrive\desktop\AIML\Python-Implementation-of-Linear-Regression\BMI\BMI.csv")

In [6]:
df = pd.DataFrame(data)

In [7]:
df.head()

   Gender  Height  Weight  Index
0    Male     174      96      4
1    Male     189      87      2
2  Female     185     110      4
3  Female     195     104      3
4    Male     149      61      3

In [8]:
features = ["Gender","Height","Weight"]
X = df[features]

   Gender  Height  Weight
0    Male     174      96
1    Male     189      87
2  Female     185     110
3  Female     195     104
4    Male     149      61